name: Pé de família
favicon: null
layout_spectrum: 0.91606
typography_spectrum: 0.6796
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#158346'
    - '#88bea0'
    - '#5e9f7b'
    - '#d4efe5'
  brandStrength: 0.5625
  lightness: 0.5625
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
